### ISSUE TITLE
knights not start

### ISSUE THREAD

**Issue by dagodax** [KaOSx/apps#46]
[dago@kaos ~]$ knights
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-dago'
Cannot mix incompatible Qt library (version 0x50501) with this library (version 0x50600)
KCrash: Application 'knights' crashing...
KCrash: Attempting to start /usr/lib/drkonqi from kdeinit
sock_file=/tmp/runtime-dago/kdeinit5__0

[1]+  Detenido                knights

**Comment by demmm** [comment]
Please note issues like these are on kde-next/Qt 5.6 (at least that is what it looks like)
Currently knight fails to build on Qt 5.6:
````
[ 93%] Building CXX object src/CMakeFiles/knights.dir/knightsadaptor.cpp.o
[ 95%] Building CXX object src/CMakeFiles/knights.dir/knightsdebug.cpp.o
[ 97%] Building CXX object src/CMakeFiles/knights.dir/knights_automoc.cpp.o
In file included from /buildsys/apps/knights/src/knights/src/knightsview.cpp:26:0:
/buildsys/apps/knights/src/knights/src/knights.h: In member function 'void Knights::KnightsView::gameOver(Knights::Color)':
/buildsys/apps/knights/src/knights/src/knights.h:52:10: error: 'void Knights::MainWindow::fileSave()' is private
     void fileSave();
          ^
/buildsys/apps/knights/src/knights/src/knightsview.cpp:136:65: error: within this context
              static_cast<MainWindow *> (window()), &MainWindow::fileSave );
                                                                 ^
src/CMakeFiles/knights.dir/build.make:705: recipe for target 'src/CMakeFiles/knights.dir/knightsview.cpp.o' failed
make[2]: *** [src/CMakeFiles/knights.dir/knightsview.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:118: recipe for target 'src/CMakeFiles/knights.dir/all' failed
make[1]: *** [src/CMakeFiles/knights.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
